Make the footer a bit better
theforumhelpers/theforumhelpers.github.io pull request #162
Opened 2021-05-09 18:24 UTC by gosoccerboy5

### Resolves:

_What Github issue does this resolve (please include link)? Do NOT create a Pull Request for a major issue that you have not been assigned to unless you are a part of the editors team for this repo._
resolves #89
It also resolves an issue on my machine where there's footer overflow that looks bad.
Screenshot of current tfh build:
<img width="731" alt="Screen Shot 2021-05-08 at 9 58 08 PM" src="https://user-images.githubusercontent.com/82768218/117559149-917db280-b048-11eb-837e-9799e9d47d23.png">

### Changes:

_Describe what this Pull Request does. Be sure to include a brief description of the issue the Pull Requests solves too._
See above, I guess

### Local Tests:

_Did you test this locally? Example: I tested this via GitHub Desktop and everything looked fine._
I tested locally, it looks fine. I would appreciate if anyone else could check it out [(branch here)](https://github.com/gosoccerboy5/theforumhelpers.github.io/tree/fix-footer)
screenshot of my updates:
<img width="1208" alt="Screen Shot 2021-05-08 at 9 56 17 PM" src="https://user-images.githubusercontent.com/82768218/117559131-5bd8c980-b048-11eb-8fde-30bd7d992226.png">

If you don't like my changes, just tell me and I can make a new PR with https://github.com/gosoccerboy5/theforumhelpers.github.io/tree/fix-footer-take-two

2021-05-09 18:49 UTC, FunctionalMetatable approved these changes
looks good to me

2021-05-09 18:52 UTC, gosoccerboy5 commented
> looks good to me

now I have to stand up to the test of accio and leahcimto..

2021-05-09 18:53 UTC, FunctionalMetatable commented
> > looks good to me
> 
> now I have to stand up to the test of accio and leahcimto..

-insert dramatic music here-

2021-05-09 18:55 UTC, gosoccerboy5 commented
> -insert dramatic music here -

how was it marked off topic so fast?!

2021-05-09 19:05 UTC, gosoccerboy5 commented
> > > looks good to me
> > 
> > 
> > now I have to stand up to the test of accio and leahcimto..
> 
> -insert dramatic music here-

ikr

2021-05-09 19:07 UTC, Shluffy reviewed
You cann use `//` on line 300 if it is only one line

2021-05-09 19:09 UTC, gosoccerboy5 commented
> You can use `//` on line 300 if it is only one line

This is CSS, not Javascript

2021-05-09 20:18 UTC, Accio1 commented
I'm not sure why every link has to be wrapped in a `<div>` tag. Changing the line-height property for the footer should suffice if `<br>` tags create too much of a gap. I think a line height of 30px should be enough to make a gap without being too spaced out.

2021-05-09 20:39 UTC, leahcimto requested changes
^^

doing request changes github thing for the comment above

2021-05-09 21:06 UTC, gosoccerboy5 commented
> ^^
> 
> doing request changes github thing for the comment above

understandable. do you guys make changes, or should I commit to the branch?

2021-05-09 21:10 UTC, gosoccerboy5 commented
> I'm not sure why every link has to be wrapped in a `<div>` tag. Changing the line-height property for the footer should suffice if `<br>` tags create too much of a gap. I think a line height of 30px should be enough to make a gap without being too spaced out.

Wow, I'm an idiot. That worked perfectly, thanks.

2021-05-09 21:13 UTC, leahcimto approved these changes
Looking great now!

Also sorry if this is a bit unrelated but is the underline for the links in the footer ticking anyone else off?

2021-05-09 21:15 UTC, gosoccerboy5 commented
> Also sorry if this is a bit unrelated but is the underline for the links in the footer ticking anyone else off?

Thanks! I can change that rn if you want.. (it seems fine to me)

2021-05-09 21:16 UTC, leahcimto commented
> Thanks! I can change that rn if you want.. (it seems fine to me)

No, you don't have to :P I was just wondering if that was just me

2021-05-09 22:17 UTC, Accio1 approved these changes
Looks good! Thanks for doing this!

2021-05-09 22:18 UTC, merged

2021-05-25 20:01 UTC, Shluffy commented
no longer `pr - status: changes requested`