cursor: pointer;
theforumhelpers/theforumhelpers.github.io pull request #231
Opened 2021-06-11 16:02 UTC by CodeGuy92

### Resolves:

Fixes #187

### Changes:

Makes all buttons change your cursor to "pointer" icon.

### Local Tests:

No, but nothing can go wrong.

2021-06-11 16:03 UTC, gosoccerboy5 commented
ok nice, it seems cool

2021-06-11 16:21 UTC, BarelySmooth requested changes
It looks good! But can you place this somewhere above? This is currently below the footer and right now, there are no buttons in the footer.

2021-06-11 17:00 UTC, Accio1 requested changes
I agree with @BarelySmooth. Since this applies to all buttons, it should be near the top of the stylesheet.

2021-06-14 13:51 UTC, CodeGuy92 commented
@Accio1 done

2021-06-14 13:54 UTC, Accio1 commented
@CodeGuy92 Since the button does not just apply to the navbar, it shouldn't be in with the navbar CSS either. It should be just before the code for the navbar.

2021-06-14 13:54 UTC, BarelySmooth commented on resources/stylesheet.css
> +button {
but this is in the header part. Could you move it a little up?

2021-06-17 18:58 UTC, CodeGuy92 commented
@Accio1 is this the final commit

2021-06-17 19:02 UTC, BarelySmooth approved these changes
This looks fine! 😃

2021-06-17 20:52 UTC, gosoccerboy5 approved these changes
looks great

2021-06-17 21:35 UTC, leahcimto approved these changes
Looks good!

2021-06-21 05:57 UTC, BarelySmooth commented
@CodeGuy92 For some reason the fork you are trying to merge from no longer exists. (That is probably why the test failed).

@Accio1 Is merging this still possible?

2021-06-21 13:37 UTC, gosoccerboy5 commented
My goodness, can't we have @accio1 just write some CSS and slap it into the file? We've been waiting 10 days, there were a bunch of changes requested, and now the branch is deleted. Why don't we put this behind us and have someone with write access edit the files or at least make a new PR?

2021-06-21 15:22 UTC, CodeGuy92 commented
> @CodeGuy92 For some reason the fork you are trying to merge from no longer exists. (That is probably why the test failed).
> 
> @Accio1 Is merging this still possible?

What? It is? Where did my fork go?

2021-06-21 15:25 UTC, closed without merging

2021-06-21 15:27 UTC, CodeGuy92 commented
https://github.com/theforumhelpers/theforumhelpers.github.io/pull/253

2021-06-25 18:11 UTC, Accio1 commented
> My goodness, can't we have @Accio1 just write some CSS and slap it into the file? We've been waiting 10 days, there were a bunch of changes requested, and now the branch is deleted. Why don't we put this behind us and have someone with write access edit the files or at least make a new PR?

Please appreciate that I have been very busy the past couple weeks working on completing my school year. This was not a priority, so that is why I didn't have time to review it. Please be patient.

2021-06-25 19:39 UTC, gosoccerboy5 commented
> > My goodness, can't we have @Accio1 just write some CSS and slap it into the file? We've been waiting 10 days, there were a bunch of changes requested, and now the branch is deleted. Why don't we put this behind us and have someone with write access edit the files or at least make a new PR?
> 
> @gosoccerboy5 Please appreciate that I have been very busy the past couple weeks working on completing my school year. This was not a priority, so that is why I didn't have time to review it. Please be patient.

I apologize for being irrational like that..