Make header links collapsible on mobile
theforumhelpers/theforumhelpers.github.io pull request #262
Opened 2021-06-30 01:08 UTC by Accio1

### Resolves:

Resolves #236 

### Changes:

-Add two new functions to imports.js: expandHeader() and collapseHeader()
-expandHeader() expands the dropdown that appears on screens <1154px and collapseHeader collapses the dropdown.
-On desktop, hovering on the dropdown will open it and hovering off it will close it.
-On mobile, clicking on the dropdown will open it and clicking somewhere else will close it.

### Local Tests:

Tested locally, additionally I tested this on my fork of the repo on mobile. This fork can be found here: https://accio1.github.io/theforumhelpers.github.io

@gosoccerboy5 @leahcimto

2021-06-30 11:56 UTC, leahcimto approved these changes

2021-06-30 12:05 UTC, leahcimto commented
also i think that this was only a bug on safari iirc

2021-06-30 12:10 UTC, BarelySmooth commented
I'm not sure if this is intentional, but now the dropdown menu doesn't work on desktop. Was this intended?

2021-06-30 12:22 UTC, leahcimto requested changes
Sorry, undoing my approval. @BarelySmooth said this does not work on desktop now and I'm having the same issue.

2021-06-30 12:43 UTC, leahcimto commented
it also did not work on safari mobile for me

2021-06-30 12:47 UTC, Accio1 commented
@leahcimto @BarelySmooth 
Whoops, I made a last minute change that I evidently forgot to test. It should be working now on both desktop and mobile.

2021-06-30 12:52 UTC, BarelySmooth approved these changes
Yep, it works on desktop now, I didn't test it on Safari though :P

2021-06-30 13:38 UTC, gosoccerboy5 commented
Looks nice with responsive design mode 👍

2021-06-30 17:17 UTC, leahcimto approved these changes
Works on desktop chrome and safari, and mobile safari.

2021-06-30 17:30 UTC, gosoccerboy5 approved these changes
forgot to approve lol

2021-07-01 01:08 UTC, Accio1 commented
Merging! Thanks everyone for reviewing and catching my bug!

2021-07-01 01:09 UTC, merged