New curators and 3 curators promoted to manager
theforumhelpers/theforumhelpers.github.io pull request #28
Opened 2020-11-28 22:46 UTC by leahcimto

Hi! I updated curators.json and managers.json with new curators and I moved the curators that were recently promoted to managers.json.

2020-12-03 02:19 UTC, Accio1 requested changes
@leahcimto Curators List looks good. Please make the indicated changes to the Managers list, then I will review this again and hopefully merge it soon!

2020-12-03 02:19 UTC, Accio1 commented on Forum_Helpers/managers.json
> +        "name": "fdreerf",
Fdreerf should be before xXRedTheCoderXx

2020-12-03 02:19 UTC, Accio1 commented on Forum_Helpers/managers.json
>      }
Please add Paddle2See

2020-12-03 12:29 UTC, leahcimto commented
Thanks, will add those changes today.

2020-12-03 12:57 UTC, leahcimto commented
I made the changes, let me know if anything else should be changed.

2020-12-03 16:13 UTC, Accio1 commented
I'm at school right now so I can't review it. I'm labelling it as unreviewed so that I remember to review it tonight.

2020-12-04 02:28 UTC, Accio1 approved these changes
Thanks for doing this! Looking over it briefly, it looks good to merge!

2020-12-04 02:30 UTC, merged

2020-12-04 02:34 UTC, Accio1 commented
This is partially my fault for not checking, but in the future, please make sure to remove the comma after the final item in the list, as that causes an error when the site tries to load it.