Update Forum Helpers JSON Files
theforumhelpers/theforumhelpers.github.io pull request #303
Opened 2021-12-31 23:47 UTC by leahcimto

### Resolves:
#302 

### Changes:

- Moves managers.json and curators.json to originalManagers.json and originalCurators.json.
- Updates managers.json and curators.json with new studio curators list.
- managers.json and curators.json now have a new JSON key that states if the user is in the original studio.
- Adds new bios to managers.json and curators.json that were requested on the [TFH-Bios](https://scratch.mit.edu/users/TFH-Bios/) Scratch account

### Local Tests:
Not possible, however I tested this on my fork with GitHub Pages (https://leahcimto.github.io/theforumhelpers.github.io/forumhelpers/) and both lists were blank, so there is clearly an error. Therefore, this PR is blocked.

2022-01-01 20:36 UTC, leahcimto commented
If anyone could help look through the JSON files and let me know of any errors, that would be much appreciated.

2022-01-07 21:49 UTC, leahcimto commented
I'm starting to wonder if this is not an issue with the json, after looking it over it looks fine.

2022-01-18 19:10 UTC, FunctionalMetatable commented
> I'm starting to wonder if this is not an issue with the json, after looking it over it looks fine.

![image](https://user-images.githubusercontent.com/67440879/150002724-aa18e158-31da-41c7-80af-d1278b902f30.png)
Incorrect URL for managers.json.

2022-01-18 23:35 UTC, leahcimto commented
@FunctionalMetatable 

<img width="1235" alt="Screen Shot 2022-01-18 at 6 34 19 PM" src="https://user-images.githubusercontent.com/68165163/150035834-448ce654-a1a7-4bea-9404-f1edb037e9dd.png">

It's in the folder though

2022-01-19 07:02 UTC, CST1229 commented
![](https://user-images.githubusercontent.com/68464103/150080051-2da9c737-ef7a-4f6c-a317-3dde09ebd67a.png)
You are trying to get `https://leahcimto.github.io/forumhelpers/managers.json`, but it should be `https://leahcimto.github.io/theforumhelpers.github.io/forumhelpers/managers.json`.

2022-01-19 21:25 UTC, FunctionalMetatable commented
yeah

2022-01-19 23:46 UTC, leahcimto commented
@CST1229 @FunctionalMetatable Thank you! I have tested it now, and it looks good! I need to add two more users though and remove one, and then I will mark this as ready for review!

2022-01-19 23:53 UTC, leahcimto commented
Okay, I added the two new users. The user banananology was in the past studio, but on a different account. I still marked them as an original user.

2022-01-19 23:53 UTC, leahcimto commented
This is now ready for review.

2022-01-19 23:53 UTC, leahcimto commented
This is now ready for review.

2022-01-31 15:23 UTC, Accio1 commented
I'm assuming the users are correct. Small request: just to save on space when this ends up being hosted on a server for TFH Dashboard (hopefully soon). Could, the "original" key be replaced with something shorter, such as "og" or something, and true/false replaced with t/f.

2022-01-31 15:24 UTC, Accio1 requested changes
I'm assuming the users are correct. Small request: just to save on space when this ends up being hosted on a server for TFH Dashboard (hopefully soon). Could, the "original" key be replaced with something shorter, such as "og" or something, and true/false replaced with t/f.

2022-01-31 18:13 UTC, CST1229 commented
> I'm assuming the users are correct. Small request: just to save on space when this ends up being hosted on a server for TFH Dashboard (hopefully soon). Could, the "original" key be replaced with something shorter, such as "og" or something, and true/false replaced with t/f.

Also minify the JSON file.

2022-01-31 22:38 UTC, leahcimto commented
@Accio1 Done

2022-02-12 23:01 UTC, leahcimto commented
@Accio1 bump

2022-02-23 00:22 UTC, leahcimto commented
Added a new curator and fixed an error.

2022-02-25 02:23 UTC, Accio1 commented
I'm going to block this for now pending the next TFH dashboard release to make sure the database gets filled with the correct information. The next TFH dashboard release should be coming soon, so stay tuned.

2022-02-25 15:14 UTC, CST1229 commented
> I'm assuming the users are correct. Small request: just to save on space when this ends up being hosted on a server for TFH Dashboard (hopefully soon). Could, the "original" key be replaced with something shorter, such as "og" or something, and true/false replaced with t/f.

@Accio1 I think true and false could be replaced with 1 and 0 since they're shorter than strings and they're even equivalent in some languages.

2022-03-02 22:01 UTC, leahcimto commented
two users should be promoted

2022-03-15 19:28 UTC, leahcimto commented
New curators need to be added. I won’t have access to my computer until tomorrow so I hope to do it then.

2022-03-15 19:30 UTC, leahcimto commented
Bio for user VioletCalico:
Hello! I’m VioletCalico, an active forumer who mostly posts on Questions About Scratch and Suggestions! I also try to post on Bugs and Glitches and New Scratcher often.

2022-03-16 23:43 UTC, leahcimto commented
New users added.

2022-04-21 22:53 UTC, leahcimto commented
Needs bios for AIGamesDeveloper and mbrick2.

2022-04-27 06:40 UTC, Mbrick2 commented
What about my Bio?

2022-04-27 11:46 UTC, leahcimto commented
@Mbrick2 please be patient, it's coming. I should have time to do it this afternoon.

2022-04-30 13:01 UTC, leahcimto commented
promote wangat add Nambaseking01

2022-05-09 21:20 UTC, leahcimto commented
add ssb20 new bio
Hi, I’m Super_Scratch_Bros20, but you can call me SSB20. I’m a forumer who wants to help however I can. I can be found on Questions about Scratch, Suggestions, and sometimes Things I’m Reading and Playing. If you have any questions, feel free to contact me. Scratch On!

2022-05-16 00:51 UTC, leahcimto commented
Add bio for @Shluffy (dogsmakemehappy) #314 :
"Hi! I am dogsmakemehappy, also known as Shluffy or ShluffyMonster on other sites. I am currently inactive and I work on modding minecraft Java Edition"

2022-06-08 17:40 UTC, leahcimto commented
add new users:
[sharkode](https://scratch.mit.edu/users/sharkode) 46685332
[jackson49](https://scratch.mit.edu/users/jackson49) 18502842
[portalpower](https://scratch.mit.edu/users/portalpower) 28289107
[historical_supa](https://scratch.mit.edu/users/historical_supa) 71825463
[ScolderCreations](https://scratch.mit.edu/users/ScolderCreations) 68889501
[Adzboy](https://scratch.mit.edu/users/Adzboy) 84839537
[minikiwigeek2](https://scratch.mit.edu/users/minikiwigeek2) 27872815
[DinoMaster20](https://scratch.mit.edu/users/DinoMaster20) 44985322

2022-06-08 17:41 UTC, leahcimto commented
@leahcimto remember to do this

2022-07-17 22:54 UTC, Accio1 approved these changes
I'm trusting that this is up to date and valid JSON.

2022-07-17 22:55 UTC, merged