Updated front page
theforumhelpers/theforumhelpers.github.io pull request #33
Opened 2020-12-08 23:18 UTC by leahcimto

There is a new application system, so I updated index.html to reflect that. I also added a link for the studio instead of it saying “(there is a link in the header)”.

2020-12-10 20:37 UTC, Accio1 requested changes
A few wording changes and then this will be good to merge!

2020-12-10 20:37 UTC, Accio1 commented on index.html
> +			<p style="margin-left:200px;margin-right:200px">Once you submit an application, a few of the studio curators and managers will look at your application and say if they think you would be a good fi
Please change this to: 
"Once you submit an application, a few of the studio curators and managers will look at your application and say if they think you would be a good fit for this group. If several curators and managers think that you would make a good fit, your application will be accepted and you will be informed and invited to the studio. If they don't think you are a good fit at this time, or if a week passes without you being accepted, then your application will be rejected and you will get a message saying how you can improve. If your application has been rejected, feel free to re apply in two weeks, keeping in mind the feedback that you were given. While your application is being discussed, feel free to look at the discussion, but please don't comment on it, or you will lose a point and your chances of being accepted will be lower. Feel free to withdraw your application at any time, but keep in mind that you will have to wait 2 weeks before re applying if you withdraw your application. There is currently a limit of 6 pending applications at a time."

2020-12-11 00:07 UTC, leahcimto commented
Thanks, I’ll do that when I have time.

2020-12-11 00:22 UTC, leahcimto commented
@Accio1 Done, let me know if anything else should be changed.

2020-12-11 00:36 UTC, Accio1 approved these changes
Thank you! Merging!

2020-12-11 00:37 UTC, merged